server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://39.108.48.226:3306/mall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

mybatis:
  mapper-locations:
    - classpath:com/**/mapper/*.xml, mapper/*.xml
    - classpath*:com/**/mapper/*.xml

